"$schema" = "https://starship.rs/config-schema.json"

[aws]
symbol = "îŒ½ "
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"

[buf]
symbol = "ï’ "
format = "\\[[$symbol($version)]($style)\\]"

[bun]
symbol = "î¯ "
format = "\\[[$symbol($version)]($style)\\]"

[c]
symbol = "î˜ "
format = "\\[[$symbol($version(-$name))]($style)\\]"

[cpp]
symbol = "î˜ "
format = "\\[[$symbol($version(-$name))]($style)\\]"

[cmake]
symbol = "î” "
format = "\\[[$symbol($version)]($style)\\]"

[conda]
symbol = "ï„Œ "
format = "\\[[$symbol$environment]($style)\\]"

[crystal]
symbol = "î˜¯ "
format = "\\[[$symbol($version)]($style)\\]"

[dart]
symbol = "î˜ "
format = "\\[[$symbol($version)]($style)\\]"

[deno]
symbol = "îŸ€ "
format = "\\[[$symbol($version)]($style)\\]"

[directory]
read_only = " ó°Œ¾"

[docker_context]
symbol = "ïŒˆ "
format = "\\[[$symbol$context]($style)\\]"

[elixir]
symbol = "î˜­ "
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"

[elm]
symbol = "î˜¬ "
format = "\\[[$symbol($version)]($style)\\]"

[fennel]
symbol = "îš¯ "
format = "\\[[$symbol($version)]($style)\\]"

[fortran]
symbol = "îŸ "
format = "\\[[$symbol($version)]($style)\\]"

[fossil_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[gcloud]
symbol = "îŸ± "
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"

[git_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[git_commit]
tag_symbol = " ï’ "
format = "\\[[\\($hash$tag\\)]($style)\\]"

[golang]
symbol = "î˜§ "
format = "\\[[$symbol($version)]($style)\\]"

[gradle]
symbol = "î™  "
format = "\\[[$symbol($version)]($style)\\]"

[guix_shell]
symbol = "ïŒ¥ "
format = "\\[[$symbol]($style)\\]"

[haskell]
symbol = "î· "
format = "\\[[$symbol($version)]($style)\\]"

[haxe]
symbol = "î™¦ "
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
symbol = "ï˜ "
format = "\\[[$symbol$branch]($style)\\]"

[hostname]
ssh_symbol = "î¬ "
format = "\\[[$ssh_symbol($hostname)]($style)\\] "

[java]
symbol = "î‰– "
format = "\\[[$symbol($version)]($style)\\]"

[julia]
symbol = "î˜¤ "
format = "\\[[$symbol($version)]($style)\\]"

[kotlin]
symbol = "î˜´ "
format = "\\[[$symbol($version)]($style)\\]"

[lua]
symbol = "î˜  "
format = "\\[[$symbol($version)]($style)\\]"

[memory_usage]
symbol = "ó°› "
format = "\\[$symbol[$ram( | $swap)]($style)\\]"

[meson]
symbol = "ó°”· "
format = "\\[[$symbol$project]($style)\\]"

[nim]
symbol = "ó°†¥ "
format = "\\[[$symbol($version)]($style)\\]"

[nix_shell]
symbol = "ïŒ“ "
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"

[nodejs]
symbol = "îœ˜ "
format = "\\[[$symbol($version)]($style)\\]"

[ocaml]
symbol = "î™º "
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[os]
format = "\\[[$symbol]($style)\\]"

  [os.symbols]
  Alpaquita = "îª¢ "
  Alpine = "ïŒ€ "
  AlmaLinux = "ïŒ "
  Amazon = "ï‰° "
  Android = "ï…» "
  AOSC = "ïŒ "
  Arch = "ïŒƒ "
  Artix = "ïŒŸ "
  CachyOS = "ïŒƒ "
  CentOS = "ïŒ„ "
  Debian = "ïŒ† "
  DragonFly = "îŠ "
  Elementary = "ïŒ‰ "
  Emscripten = "ïˆ… "
  EndeavourOS = "ï†— "
  Fedora = "ïŒŠ "
  FreeBSD = "ïŒŒ "
  Garuda = "ó°›“ "
  Gentoo = "ïŒ "
  HardenedBSD = "ó°Œ "
  Illumos = "ó°ˆ¸ "
  Ios = "ó°€· "
  Kali = "ïŒ§ "
  Linux = "ïŒš "
  Mabox = "î¬© "
  Macos = "ïŒ‚ "
  Manjaro = "ïŒ’ "
  Mariner = "ï‡ "
  MidnightBSD = "ï†† "
  Mint = "ïŒ "
  NetBSD = "ï€¤ "
  NixOS = "ïŒ“ "
  Nobara = "ï€ "
  OpenBSD = "ó°ˆº "
  openSUSE = "ïŒ” "
  OracleLinux = "ó°Œ· "
  Pop = "ïŒª "
  Raspbian = "ïŒ• "
  Redhat = "ïŒ– "
  RedHatEnterprise = "ïŒ– "
  RockyLinux = "ïŒ« "
  Redox = "ó°€˜ "
  Solus = "ó° ³ "
  SUSE = "ïŒ” "
  Ubuntu = "ïŒ› "
  Unknown = "ïˆ­ "
  Void = "ïŒ® "
  Windows = "ó°² "
  Zorin = "ïŒ¯ "

[package]
symbol = "ó°— "
format = "\\[[$symbol$version]($style)\\]"

[perl]
symbol = "î™¾ "
format = "\\[[$symbol($version)]($style)\\]"

[php]
symbol = "î˜ˆ "
format = "\\[[$symbol($version)]($style)\\]"

[pijul_channel]
symbol = "ï˜ "
format = "\\[[$symbol$channel]($style)\\]"

[pixi]
symbol = "ó°— "
format = "\\[[$symbol$version( $environment)]($style)\\]"

[python]
symbol = "îˆµ "
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"

[rlang]
symbol = "ó°Ÿ” "
format = "\\[[$symbol($version)]($style)\\]"

[ruby]
symbol = "î‘ "
format = "\\[[$symbol($version)]($style)\\]"

[rust]
symbol = "ó±˜— "
format = "\\[[$symbol($version)]($style)\\]"

[scala]
symbol = "îœ· "
format = "\\[[$symbol($version)]($style)\\]"

[status]
symbol = "ï‘§ "
format = "\\[[$symbol$status]($style)\\]"

[swift]
symbol = "î• "
format = "\\[[$symbol($version)]($style)\\]"

[xmake]
symbol = "î” "
format = "\\[[$symbol($version)]($style)\\]"

[zig]
symbol = "îš© "
format = "\\[[$symbol($version)]($style)\\]"

[azure]
format = "\\[[$symbol($subscription)]($style)\\]"

[battery]
format = "\\[[$symbol$percentage]($style)\\]"

[cmd_duration]
format = "\\[[â± $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"

[container]
format = "\\[[$symbol \\[$name\\]]($style)\\]"

[daml]
format = "\\[[$symbol($version)]($style)\\]"

[direnv]
format = "\\[[$symbol$loaded/$allowed]($style)\\]"

[dotnet]
format = "\\[[$symbol($version)(ğŸ¯ $tfm)]($style)\\]"
detect_extensions = ['csproj', 'sln', 'slnx']

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[fossil_metrics]
format = "\\[[+$added]($added_style)\\]\\[[-$deleted]($deleted_style)\\]"

[git_metrics]
format = "\\[[+$added]($added_style)\\]\\[[-$deleted]($deleted_style)\\]"

[git_state]
format = "\\[[$state ($progress_current/$progress_total)]($style)\\]"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[gleam]
format = "\\[[$symbol($version)]($style)\\]"

[helm]
format = "\\[[$symbol($version)]($style)\\]"

[jobs]
format = "\\[[$symbol$number]($style)\\]"

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[localip]
format = "\\[[$localipv4]($style)\\]"

[mise]
format = "\\[[$symbol$health]($style)\\]"

[mojo]
format = "\\[[$symbol($version)]($style)\\]"

[nats]
format = "\\[[$symbol$name]($style)\\]"

[netns]
format = "\\[[$symbol \\[$name\\]]($style)\\]"

[odin]
format = "\\[[$symbol($version )]($style)\\]"

[opa]
format = "\\[[$symbol($version)]($style)\\]"

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"

[purescript]
format = "\\[[$symbol($version)]($style)\\]"

[quarto]
format = "\\[[$symbol($version)]($style)\\]"

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"

[red]
format = "\\[[$symbol($version)]($style)\\]"

[shell]
format = "\\[[$indicator]($style)\\]"

[singularity]
format = "\\[[$symbol\\[$env\\]]($style)\\]"

[solidity]
format = "\\[[$symbol($version)]($style)\\]"

[spack]
format = "\\[[$symbol$environment]($style)\\]"

[sudo]
format = "\\[[as $symbol]($style)\\]"

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"

[time]
format = "\\[[$time]($style)\\]"

[typst]
format = "\\[[$symbol($version)]($style)\\]"

[username]
format = "\\[[$user]($style)\\]"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vcsh]
format = "\\[vcsh [$symbol$repo]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"
